language: node_js
node_js:
    - node
env:
    global:
        - CC_TEST_REPORTER_ID=f8891063bd8501e3f74e5cedf972e88b59c1a7b90fc25c4c4fcdefa8147a20b0
before_script:
    - curl -L
      https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - yarn test --coverage
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
    email: false
